# Generated by Django 4.2.16 on 2024-11-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Date of the appointment', verbose_name='Day of the appointment')),
                ('time', models.TimeField(help_text='Time of the appointment', verbose_name='Time of the appointment')),
                ('patient', models.CharField(help_text='Patients full name', max_length=100, verbose_name='Patients full name')),
                ('notes', models.TextField(blank=True, help_text='Notes', max_length=200, null=True, verbose_name='Notes')),
            ],
        ),
    ]
