# Generated by Django 4.2.16 on 2024-11-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, unique=True, verbose_name='Full Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('date_of_birth', models.DateField(help_text='Date of birth', verbose_name='Date of birth')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Phone number')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='Email')),
                ('insurance_number', models.CharField(max_length=200, unique=True, verbose_name='Insurance number')),
                ('current_medications', models.TextField(help_text='Current medications', verbose_name='Current medications')),
                ('medication_history', models.TextField(help_text='Medication history', verbose_name='Medication history')),
                ('health_status', models.CharField(max_length=200, verbose_name='Health status or diagnosis')),
                ('symptoms', models.TextField(help_text='Symptoms', verbose_name='Symptoms')),
                ('medical_history', models.TextField(help_text='Medical history', verbose_name='Medical history')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, verbose_name='Filename')),
                ('patient', models.ManyToManyField(to='main.patient')),
            ],
        ),
    ]
