# Generated by Django 4.2.16 on 2024-11-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patient_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='day',
            new_name='date',
        ),
    ]
