# Generated by Django 4.2.16 on 2024-11-20 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_rename_day_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
