# Generated by Django 4.2.17 on 2025-01-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default=None, max_length=200, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
