# Generated by Django 4.2.17 on 2025-01-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_patient_address_patient_document_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Address'),
        ),
    ]
